# Generated by Django 4.2.3 on 2023-07-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shart_name', models.CharField(max_length=20)),
                ('shart_color', models.CharField(max_length=20)),
                ('shart_price', models.IntegerField()),
                ('all_sart', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
                ('student_cgpa', models.FloatField()),
            ],
        ),
    ]
