# Generated by Django 4.2.3 on 2023-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shart',
            name='all_sart',
            field=models.IntegerField(choices=[(1, 'M_shart'), (2, 'L_shart'), (3, 'XL_shart'), (4, 'XXL_shart'), (5, 'XXXL_shart')], max_length=30),
        ),
    ]
